# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window_Main(object):
    def setupUi(self, Window_Main):
        Window_Main.setObjectName("Window_Main")
        Window_Main.resize(892, 659)
        self.centralwidget = QtWidgets.QWidget(Window_Main)
        self.centralwidget.setObjectName("centralwidget")
        Window_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_pre_process = QtWidgets.QMenu(self.menubar)
        self.menu_pre_process.setObjectName("menu_pre_process")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_line_process = QtWidgets.QMenu(self.menubar)
        self.menu_line_process.setObjectName("menu_line_process")
        self.menu_char_recognize = QtWidgets.QMenu(self.menubar)
        self.menu_char_recognize.setObjectName("menu_char_recognize")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_recognize = QtWidgets.QMenu(self.menubar)
        self.menu_recognize.setObjectName("menu_recognize")
        Window_Main.setMenuBar(self.menubar)
        self.action_open = QtWidgets.QAction(Window_Main)
        self.action_open.setObjectName("action_open")
        self.action_close = QtWidgets.QAction(Window_Main)
        self.action_close.setObjectName("action_close")
        self.action_exit = QtWidgets.QAction(Window_Main)
        self.action_exit.setObjectName("action_exit")
        self.action_remove_noise = QtWidgets.QAction(Window_Main)
        self.action_remove_noise.setObjectName("action_remove_noise")
        self.action_text_extract = QtWidgets.QAction(Window_Main)
        self.action_text_extract.setObjectName("action_text_extract")
        self.action_line_extract = QtWidgets.QAction(Window_Main)
        self.action_line_extract.setObjectName("action_line_extract")
        self.action_tilt_correction = QtWidgets.QAction(Window_Main)
        self.action_tilt_correction.setObjectName("action_tilt_correction")
        self.action_about = QtWidgets.QAction(Window_Main)
        self.action_about.setObjectName("action_about")
        self.action_char_extract = QtWidgets.QAction(Window_Main)
        self.action_char_extract.setObjectName("action_char_extract")
        self.actionDafsd = QtWidgets.QAction(Window_Main)
        self.actionDafsd.setObjectName("actionDafsd")
        self.action_char_export_2_img = QtWidgets.QAction(Window_Main)
        self.action_char_export_2_img.setObjectName("action_char_export_2_img")
        self.action_char_export_2_text = QtWidgets.QAction(Window_Main)
        self.action_char_export_2_text.setObjectName("action_char_export_2_text")
        self.action_recognize_chars = QtWidgets.QAction(Window_Main)
        self.action_recognize_chars.setObjectName("action_recognize_chars")
        self.action_del_selected_line = QtWidgets.QAction(Window_Main)
        self.action_del_selected_line.setObjectName("action_del_selected_line")
        self.action_merged_selected_line = QtWidgets.QAction(Window_Main)
        self.action_merged_selected_line.setObjectName("action_merged_selected_line")
        self.action_del_selected_char = QtWidgets.QAction(Window_Main)
        self.action_del_selected_char.setObjectName("action_del_selected_char")
        self.action_merge_selected_char = QtWidgets.QAction(Window_Main)
        self.action_merge_selected_char.setObjectName("action_merge_selected_char")
        self.action_cut_selected_char = QtWidgets.QAction(Window_Main)
        self.action_cut_selected_char.setObjectName("action_cut_selected_char")
        self.action_cut_selected_line = QtWidgets.QAction(Window_Main)
        self.action_cut_selected_line.setObjectName("action_cut_selected_line")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_pre_process.addAction(self.action_remove_noise)
        self.menu_pre_process.addAction(self.action_text_extract)
        self.menu_help.addAction(self.action_about)
        self.menu_line_process.addAction(self.action_line_extract)
        self.menu_line_process.addAction(self.action_cut_selected_line)
        self.menu_line_process.addAction(self.action_del_selected_line)
        self.menu_line_process.addAction(self.action_merged_selected_line)
        self.menu_char_recognize.addAction(self.action_char_extract)
        self.menu_char_recognize.addAction(self.action_del_selected_char)
        self.menu_char_recognize.addAction(self.action_merge_selected_char)
        self.menu_char_recognize.addAction(self.action_cut_selected_char)
        self.menu.addAction(self.action_char_export_2_img)
        self.menu.addAction(self.action_char_export_2_text)
        self.menu_recognize.addAction(self.action_recognize_chars)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_pre_process.menuAction())
        self.menubar.addAction(self.menu_line_process.menuAction())
        self.menubar.addAction(self.menu_char_recognize.menuAction())
        self.menubar.addAction(self.menu_recognize.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(Window_Main)
        QtCore.QMetaObject.connectSlotsByName(Window_Main)

    def retranslateUi(self, Window_Main):
        _translate = QtCore.QCoreApplication.translate
        Window_Main.setWindowTitle(_translate("Window_Main", "MainWindow"))
        self.menu_file.setTitle(_translate("Window_Main", "文件"))
        self.menu_pre_process.setTitle(_translate("Window_Main", "预处理"))
        self.menu_help.setTitle(_translate("Window_Main", "帮助"))
        self.menu_line_process.setTitle(_translate("Window_Main", "文本行切分"))
        self.menu_char_recognize.setTitle(_translate("Window_Main", "字丁切分"))
        self.menu.setTitle(_translate("Window_Main", "工具"))
        self.menu_recognize.setTitle(_translate("Window_Main", "字丁识别"))
        self.action_open.setText(_translate("Window_Main", "打开"))
        self.action_open.setShortcut(_translate("Window_Main", "Ctrl+O"))
        self.action_close.setText(_translate("Window_Main", "关闭"))
        self.action_close.setShortcut(_translate("Window_Main", "Ctrl+W"))
        self.action_exit.setText(_translate("Window_Main", "退出"))
        self.action_remove_noise.setText(_translate("Window_Main", "去除噪点"))
        self.action_text_extract.setText(_translate("Window_Main", "检测文字区域"))
        self.action_line_extract.setText(_translate("Window_Main", "文本行切分"))
        self.action_tilt_correction.setText(_translate("Window_Main", "倾斜矫正"))
        self.action_about.setText(_translate("Window_Main", "关于"))
        self.action_char_extract.setText(_translate("Window_Main", "字丁切分"))
        self.actionDafsd.setText(_translate("Window_Main", "dafsd"))
        self.action_char_export_2_img.setText(_translate("Window_Main", "导出已切分的字丁图片"))
        self.action_char_export_2_text.setText(_translate("Window_Main", "导出识别字丁到文本"))
        self.action_recognize_chars.setText(_translate("Window_Main", "识别已切分的字丁"))
        self.action_del_selected_line.setText(_translate("Window_Main", "删除选中的文本行"))
        self.action_merged_selected_line.setText(_translate("Window_Main", "合并选中的文本行"))
        self.action_del_selected_char.setText(_translate("Window_Main", "删除选中的字丁"))
        self.action_merge_selected_char.setText(_translate("Window_Main", "合并选中的字丁"))
        self.action_cut_selected_char.setText(_translate("Window_Main", "切分选中的字丁"))
        self.action_cut_selected_line.setText(_translate("Window_Main", "切分选中的文本行"))

